### ISSUE TITLE
Bottom 1.5 lines cut off in printer window

### ISSUE THREAD

**Issue by quantalume** [bug400/pyilper#1]
![print-window](https://cloud.githubusercontent.com/assets/1255690/12652470/91a731d8-c5b0-11e5-96c9-2687bd3185ff.png)
Running openSUSE 42.1
KDE 5.4.3
Qt 5.5.1

Tried changing default desktop fixed-width font, but it didn't help.

**Comment by bug400** [comment]
Please exchange the file pilwidgets.py with the version attached. I 
changed the
identification of the operating system.

Am 28.01.2016 um 18:22 schrieb David Brunell:

**Comment by bug400** [comment]
Please exchange the file pilwidgets.py with the version attached. The code of detecting the operating system was modified.
[pilwidgets.zip](https://github.com/bug400/pyilper/files/110277/pilwidgets.zip)

**Comment by quantalume** [comment]
Actually, I think it was correctly detecting the OS, at least in my case. I found that everything fits in the terminal window with `self.font_height=20`.

**Comment by bug400** [comment]
Hmm, for Linux "Monospace" font is used and the font size 15 pt has the 
height
18 pt.

Am 30.01.2016 um 01:21 schrieb David Brunell:

**Comment by quantalume** [comment]
I don't have an actual font called Monospace, and I don't know which one it is substituting. Which distro are you testing on? As a workaround, I can copy the font over from Ubuntu. Perhaps in a future release, you could consider a configuration option to select the font and retrieve the font metrics from the OS.

**Comment by quantalume** [comment]
Here's some good information about default fonts: [http://seasonofcode.com/posts/how-to-set-default-fonts-and-font-aliases-on-linux.html](http://seasonofcode.com/posts/how-to-set-default-fonts-and-font-aliases-on-linux.html)

On my system:

```
~> fc-match "Monospace"
SourceCodePro-Medium.otf: "Source Code Pro" "Medium"
~> 
```

I'll edit ~/.config/fontconfig/fonts.conf as suggested in the article to set the default monospace font to something compatible with PyIlper

**Comment by bug400** [comment]
I'ill try to make the terminal/printer font configurable.

Am 30.01.2016 um 20:16 schrieb David Brunell:

**Comment by quantalume** [comment]
There's also this: [http://pyqt.sourceforge.net/Docs/PyQt4/qfontmetrics.html](http://pyqt.sourceforge.net/Docs/PyQt4/qfontmetrics.html). Use the OS default monospace font and then call QFontMetrics.
