### ISSUE TITLE
Changing size of HP82162A output

### ISSUE THREAD

**Issue by hth313** [bug400/pyilper#3]
The new HP8216A printer output is very nice, thanks!

However, I wish the output could be made larger, the font size looks a bit small on my screen.

It is readable, but characters are smaller than everything else and it think it should look cooler by increasing the size, giving it more impact.

**Comment by bug400** [comment]
It is not configurable in the GUI at the moment. You can alter the configuration parameter "pyilper_hp82162a_pixelsize" parameter in the pyILPER configuration file. Please use only integers. You find the location of the configuration file "pyilper2" documented in the troubleshooting section of the user manual.
What is your experience with different pixel sizes. What pixel size range would be applicable for a GUI configuation? Unfortunately I got no feedback for the HP82162A in the beta test.

**Comment by hth313** [comment]
I tried to increase it to 2 and it made a big difference. It is acceptable size to me, but on the limit of being too big. On my screen I would say 1 and 2 for pixel size would be extremes for practical use. I would probably opt for 1.75 (if non-integers were allowed) as ideal for me on my setup.

**Comment by bug400** [comment]
Ok, I put it on the backlog for the next release. But due to technical reasons I am restricted to integers.

**Comment by hth313** [comment]
I am actually quite satisfied with the current way. I do not expect that I want to change this once configured. Not having it in the GUI is fine with me.

More choices would have been nice, but if that is not possible then there is not much to do. I will close this.

**Comment by bug400** [comment]
The last commit introduced the GUI configuration of the dot size and keeping the current scroll position on resize as well. You may test it. Please read the [Installation instruction](https://github.com/bug400/pyilper/blob/master/INSTALL.md) how to install development versions.
pyILPER 1.7.1 will be a maintenance release. I do not have a schedule for a release up to now because I hope to get  more feedback for the 1.7.0 version.

**Comment by bug400** [comment]
Fixed in 1.7.1 production.
