### ISSUE TITLE
Cannot read lif image created with 9114A

### ISSUE THREAD

**Issue by hth313** [bug400/pyilper#4]
(Not sure if it belongs here or should go to lifutils)

A long time ago I saved my magnetic card collection to a 9114A floppy and transferred it to a host computer using `dd` (using a hacked driver for NetBSD). Now I try to mount this lif image with pyilper, but `READP` gives an error trying to load a file and `lifget` gets garbage out. The directory looks fine both to pyilper and the HP-41.

`lifheader` gives sensible output, are there anything obvious that I am doing wrong?
Are there any other tools to assist in trying to decipher what is happening?

At the time I could create another floppy with `dd` and have it work on the 9114A.

Looking at the raw image in Emacs shows that there are sensible data inside it, though of course I have not idea if pointers, blocks and layout makes sense.

**Comment by bug400** [comment]
How did you extract files from and insert files to the dd image at that times?
What happens, if you try to view the file content in pyILPER?
`lifheader` displays the header of lif files and is not applicable for lif image files.
You could use the [liftool utility](https://github.com/cgottheimer/liftool) to analyze your file further.

**Comment by hth313** [comment]
I managed to solve the problem, `dd` (with my kernel fix) apparently interspersed records (4096 bytes) with empty records, so a simple hack to take every second record solved the issue. I do not know if it was due to that it took the second surface of the floppy in a different order or invented them on its own (bug), or a combination of those.

I do not care as it works now, I will close this issue.
