### ISSUE TITLE
HP Portable (110) / Plus Support

### ISSUE THREAD

**Issue by w0k3** [bug400/pyilper#5]
Hello,

I've tested pyilper with _110 Plus_ and it mostly works but mounting an existing image does not, because it checks the image for _LIF type 1 medium_ header before mounting.

I can even mount a proper LIF image (which cannot be read by 110), DOS format it, read and write it and it looks like everything works, until I unmount the (now non-LIF) image and try to mount it again - pyilper refuses to do so, because it is no longer a LIF image.

Would you consider adding a DOS image support, at least by adding an option to skip the LIF check and directory listing, i.e. mounting a raw image with whatever the user wants?

**Comment by bug400** [comment]
It took some time for me to understand the use case because I am not familiar with the 110 Plus. I think, you would like to use pyILPER as a virtual disk drive for the HP 110 Plus [as described here for the ILPer software ](http://www.jeffcalc.hp41.eu/hpplus/index.html). I have to investigate this issue. Am I right?

**Comment by w0k3** [comment]
Indeed. It looks like the virtual drive would work fine, if it was possible to skip the LIF check (which is probably present for the file listing GUI).

**Comment by bug400** [comment]
Supporting this feature required some more effort. Therefore I created a new device type "raw drive". It has just been checked into this repository. If you would like to test this feature, install the latest github version of pyilper as specified at the bottom page of the installation instructions. tHEN add the raw drive device to your device tab with the "HP-IL virtual device configuration" entry in the "File" menu. Please mind the documentation of the raw drive in the pyILPER manual.

**Comment by w0k3** [comment]
Thank you very much for all the effort, I will test it as soon as possible.

**Comment by w0k3** [comment]
Sorry it took me so long to test this. Both read and write operations work, pre-formatted images work, multiple drives work, drive-to-drive copying works, DOS-Box modified images work.

Only issue I have found so far is swapping the image files - when I use the change button to select different image file, pyILPER shows the new image file path but still responds with old image file, needs a restart to actually use the new one.

**Comment by bug400** [comment]
Thank you very much for testing. The latest commit should fix this issue.

**Comment by w0k3** [comment]
And it does, thank you!

I also did some basic benchmarks on my Portable Plus - with Scope disabled the file read speed is about 1.2 KiB/s, with Scope enabled it's about 0.8 KiB/s. ILPer in a Windows VM (KVM) on same PC reached 0.9 KiB/s with scope disabled and just about 0.4 KiB/s with Scope enabled. The number of drives did not change the results. RAM and ROM file read speeds with same tool (a simple file reader written in C) are 80 - 120 KB/s, so about 100x IL drive speed. According to http://www.jeffcalc.hp41.eu/hpil/files/how_fast_is_hpil.pdf there is still some room for improvement (about 3 KiB/s over HP-IL could be reachable), but for file transfer to RAM disk it's quite OK as it is. Thank you again for all the effort, it's awesome how versatile this almost forgotten '85 laptop is.
